name: Run Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]
      fail-fast: false
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Check Node and npm versions
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
    
    - name: List installed packages
      run: |
        echo "Installed packages:"
        npm list --depth=0
    
    - name: Run linter
      run: |
        echo "Running ESLint..."
        npm run lint || exit 1
    
    - name: Run type check
      run: |
        echo "Running TypeScript type check..."
        npm run type-check || exit 1
    
    - name: Run unit tests
      run: |
        echo "Running unit tests..."
        npm run test:unit:ci || exit 1
    
    - name: Generate coverage report
      run: |
        echo "Generating coverage report..."
        npm run test:unit:ci -- --coverage
      continue-on-error: true
    
    - name: Upload coverage to Codecov (optional)
      uses: codecov/codecov-action@v3
      if: matrix.node-version == '20.x'
      with:
        files: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false