name: Run Tests

on:
  pull_request:
    branches: [ main, master, develop ]
  push:
    branches: [ main, master, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    env:
      CI: true
      NODE_ENV: test
    
    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Check Node and npm versions
      run: |
        node --version
        npm --version
    
    - name: Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci
    
    - name: List installed packages
      run: |
        echo "Installed packages:"
        npm list --depth=0
    
    - name: Run linter
      run: |
        echo "Running ESLint..."
        npm run lint || exit 1
    
    - name: Run type check
      run: |
        echo "Running TypeScript type check..."
        npm run type-check || exit 1
    
    - name: Run unit tests
      run: |
        echo "Running unit tests..."
        npm run test:unit:ci || exit 1